### ISSUE TITLE
Compatibility with Symfony 3.0?

### ISSUE THREAD

**Issue by bibeksigdel33** [goetas/apache-fop#6]
Is this library compatible with symfony 3.0 ?

**Comment by citadev** [comment]
Not yet.
The library is using symfony/process 2.* but symfony 3 uses  symfony/process 3.*
The new version come with a few minor changes.

If you are still interested you can take a look at the pull request I just made.

**Comment by goetas** [comment]
see https://github.com/goetas/apache-fop/pull/8
